databases:
  - name: snapdoc-db
    databaseName: snapdoc
    user: snapdoc
    plan: free

services:
  - type: web
    name: file-board
    env: docker
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: snapdoc-db
          property: connectionString
      - key: MIN_FREE_SPACE_GB
        value: 1
    disk:
      name: uploads
      mountPath: /app/instance/uploads
      sizeGB: 1